pipeline {
    agent {
        label "agent"
        // docker { 
        //     image 'docker'
        //     args '--entrypoint='
        // }
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo "Start build job"'
                sh 'pwd'
                sh 'ls -la'
                script {
                    sh 'docker build -f auth-api/auth_api/Dockerfile -t 192.168.0.101:5000/auth-api auth-api/auth_api'
                    sh 'docker push 192.168.0.101:5000/auth-api'
                }
            }
        }
        stage('Test') {
            steps {
                sh "echo 'stage test'"
            }
        }
    }
}
